### PR TITLE
Update interop.md

### PR DESCRIPTION
**Pull request by xkr47**
Fix import syntax

### CODE REVIEW

**Comment by bjansen** [comment]
Thanks!

**Comment by lucaswerkmeister** [comment]
I would have suggested `shared native` instead of `native shared`… do we have a convention on this?

And dammit, @bjansen merged it too fast :/

**Comment by bjansen** [comment]
But you would write things like:

```ceylon
native("jvm")
shared void foo() {
}
```

not:

```ceylon
shared native("jvm") void foo() {
}
```

no?

**Comment by lucaswerkmeister** [comment]
Hm, apparently I’ve actually written `native ("jvm") shared` (one line), but now that looks weird to me…

**Pull request merged**
