### PR TITLE
change information about constructors

### PR DESCRIPTION
**Pull request by Zambonifofex**
Ceylon *does have* constructors now!

### CODE REVIEW

**Comment by lucaswerkmeister** [comment]
Would you mind fixing the typo in the commit message as well?

**Comment by Zambonifofex** [comment]
@lucaswerkmeister

I would have already if I knew how to.

**Comment by lucaswerkmeister** [comment]
Oh, you’re using the GitHub web UI? If you don’t want to use CLI git, I can fix it for you…

**Comment by Zambonifofex** [comment]
If you wouldn’t mind, it’d be appreciated :smile:.

**Pull request merged**
