### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by lucaswerkmeister**
Mentioned in $483.

### CODE REVIEW

**Comment by jvasileff** [comment]
Lucas, you're too quick!

**Comment by lucaswerkmeister** [comment]
nonono dont merge I made a typo

**Comment by lucaswerkmeister** [comment]
shit

**Comment by lucaswerkmeister** [comment]
*you’re* too quick! :D

**Comment by jvasileff** [comment]
I like `$483` better anyway; GitHub shouldn't have stolen the `#` symbol.

**Pull request merged**
