### PR TITLE
XSD for overrides

### PR DESCRIPTION
**Pull request by bjansen**
Might be useful for autocompletion in IDEs, it will be available at `http://www.ceylon-lang.org/xsd/overrides`.

I think it describes everything that `com.redhat.ceylon.cmr.api.Overrides#parseOverrides` can handle.

### CODE REVIEW

**Comment by bjansen** [comment]
Hang on, we already had an XSD, but it was buried deep inside ceylon-ide-eclipse: https://github.com/ceylon/ceylon-ide-eclipse/blob/master/plugins/com.redhat.ceylon.eclipse.ui/META-INF/overrides.xsd

I'll compare them and decide which one is better.

**Comment by xkr47** [comment]
@bjansen how did it go? :smile:

**Comment by bjansen** [comment]
Still comparing... ;)

**Comment by bjansen** [comment]
Done here: https://github.com/ceylon/ceylon-lang.org/commit/ccad617b980c12ced8fb7064108ca1d1e61a550c

**Comment by FroMage** [comment]
Perhaps we should add a version to it…

**Pull request closed without merging**
